"""
ByteToken — Lazy Discovery & Memory Optimization
==================================================
Three strategies for memory-efficient atom discovery:

1. Pre-computed tables: Zero runtime cost for known tokenizers
2. Chunked lazy discovery: Process vocab in configurable chunks
3. Generator-based minimal mode: <1MB peak memory

This resolves Limitation #12 from §9.3 of the paper.

Usage:
    from bytetoken.lazy_discovery import get_atoms, LazyAtomDiscovery

    # Strategy A: Pre-computed (instant, zero memory)
    atoms = get_atoms("o200k_base", bit_width=15)

    # Strategy B: Chunked (for new tokenizers)
    lazy = LazyAtomDiscovery("new_tokenizer")
    atoms = lazy.discover(bit_width=15, chunk_size=500)

    # Strategy C: Generator (minimal memory)
    for atom_id in lazy.stream_discover(target=32768):
        process(atom_id)
"""
import os
import sys
import json
import math
import time
import gzip
from typing import List, Generator, Optional, Dict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# ── Strategy A: Pre-Computed Atom Tables ───────────────────────
# These were scanned in previous experiments. Loading them is instant
# and uses ~200KB of memory (compressed atom ID lists).

# Pre-computed non-merging atom IDs for known tokenizers.
# Format: {tokenizer: {mode: [atom_ids]}}
# These are generated by `scan_and_save()` and loaded at runtime.

_PRECOMPUTED_DIR = os.path.join(os.path.dirname(__file__), "atom_tables")
_ATOM_CACHE = {}


def _ensure_tables_dir():
    """Create atom tables directory if it doesn't exist."""
    os.makedirs(_PRECOMPUTED_DIR, exist_ok=True)


def scan_and_save(tokenizer_name: str = "o200k_base") -> str:
    """
    Scan a tokenizer and save the atom table to disk.
    
    This only needs to be run ONCE per tokenizer version.
    Returns the path to the saved file.
    """
    import tiktoken
    enc = tiktoken.get_encoding(tokenizer_name)
    
    result = {
        "tokenizer": tokenizer_name,
        "vocab_size": enc.n_vocab,
        "scanned_at": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "space_nonmerging": [],
        "all_nonmerging": [],
        "roundtrip_safe": [],
    }
    
    # Phase 1: Space-prefixed non-merging
    for i in range(enc.n_vocab):
        try:
            tok_str = enc.decode([i])
        except Exception:
            continue
        
        if tok_str.startswith(' ') and len(tok_str) >= 2 and tok_str.isprintable():
            concat = tok_str + tok_str
            try:
                ids = enc.encode(concat)
                if len(ids) == 2:
                    result["space_nonmerging"].append(i)
            except Exception:
                pass
    
    # Phase 2: Roundtrip-safe (DirectID)
    for i in range(enc.n_vocab):
        try:
            decoded = enc.decode([i])
            re_encoded = enc.encode(decoded)
            if len(re_encoded) == 1 and re_encoded[0] == i:
                result["roundtrip_safe"].append(i)
        except Exception:
            pass
    
    # Save compressed
    _ensure_tables_dir()
    filepath = os.path.join(_PRECOMPUTED_DIR, f"{tokenizer_name}.json.gz")
    with gzip.open(filepath, 'wt', encoding='utf-8') as f:
        json.dump(result, f)
    
    # Also save as plain JSON for inspection
    filepath_plain = os.path.join(_PRECOMPUTED_DIR, f"{tokenizer_name}.json")
    with open(filepath_plain, 'w') as f:
        json.dump({
            "tokenizer": result["tokenizer"],
            "vocab_size": result["vocab_size"],
            "scanned_at": result["scanned_at"],
            "space_nonmerging_count": len(result["space_nonmerging"]),
            "roundtrip_safe_count": len(result["roundtrip_safe"]),
            "space_max_bw": int(math.log2(len(result["space_nonmerging"]))) if result["space_nonmerging"] else 0,
            "did_max_bw": int(math.log2(len(result["roundtrip_safe"]))) if result["roundtrip_safe"] else 0,
        }, f, indent=2)
    
    print(f"  Saved: {filepath} ({os.path.getsize(filepath):,} bytes)")
    print(f"  Space NM: {len(result['space_nonmerging']):,}")
    print(f"  DID safe: {len(result['roundtrip_safe']):,}")
    
    return filepath


def load_precomputed(tokenizer_name: str) -> Optional[Dict]:
    """Load pre-computed atom table from disk."""
    if tokenizer_name in _ATOM_CACHE:
        return _ATOM_CACHE[tokenizer_name]
    
    filepath = os.path.join(_PRECOMPUTED_DIR, f"{tokenizer_name}.json.gz")
    if not os.path.exists(filepath):
        return None
    
    with gzip.open(filepath, 'rt', encoding='utf-8') as f:
        data = json.load(f)
    
    _ATOM_CACHE[tokenizer_name] = data
    return data


def get_atoms(tokenizer_name: str, bit_width: int = 15,
              mode: str = "space") -> List[int]:
    """
    Get atom IDs for a tokenizer, using pre-computed tables if available.
    
    Falls back to lazy discovery if no pre-computed table exists.
    
    Args:
        tokenizer_name: Name of the tiktoken tokenizer
        bit_width: Desired bit width (selects 2^bit_width atoms)
        mode: "space" for space-prefixed, "did" for DirectID
    
    Returns:
        List of atom IDs
    """
    # Try pre-computed first
    precomputed = load_precomputed(tokenizer_name)
    if precomputed:
        key = "space_nonmerging" if mode == "space" else "roundtrip_safe"
        atoms = precomputed[key]
        target = 2 ** bit_width
        if len(atoms) >= target:
            return atoms[:target]
        else:
            return atoms
    
    # Fall back to lazy discovery
    lazy = LazyAtomDiscovery(tokenizer_name)
    return lazy.discover(bit_width=bit_width, mode=mode)


# ── Strategy B: Chunked Lazy Discovery ─────────────────────────

class LazyAtomDiscovery:
    """
    Memory-efficient atom discovery using chunked vocabulary scanning.
    
    Instead of loading all tokens at once, processes the vocabulary in
    configurable chunks, stopping as soon as enough atoms are found.
    
    Memory usage: O(chunk_size) instead of O(vocab_size)
    """
    
    def __init__(self, tokenizer_name: str = "o200k_base"):
        import tiktoken
        self.enc = tiktoken.get_encoding(tokenizer_name)
        self.tokenizer_name = tokenizer_name
        self.vocab_size = self.enc.n_vocab
    
    def discover(self, bit_width: int = 15, chunk_size: int = 1000,
                 mode: str = "space") -> List[int]:
        """
        Discover atoms in chunks with early termination.
        
        Stops as soon as 2^bit_width atoms are found.
        
        Args:
            bit_width: Target bit width
            chunk_size: Number of tokens to process per chunk
            mode: "space" for space-prefixed, "did" for roundtrip-safe
        
        Returns:
            List of atom IDs (at most 2^bit_width)
        """
        target = 2 ** bit_width
        atoms = []
        chunks_processed = 0
        
        for start in range(0, self.vocab_size, chunk_size):
            end = min(start + chunk_size, self.vocab_size)
            chunks_processed += 1
            
            for i in range(start, end):
                if mode == "space":
                    if self._is_space_nonmerging(i):
                        atoms.append(i)
                elif mode == "did":
                    if self._is_roundtrip_safe(i):
                        atoms.append(i)
                
                if len(atoms) >= target:
                    return atoms[:target]
        
        return atoms
    
    def stream_discover(self, target: int = 32768,
                        mode: str = "space") -> Generator[int, None, None]:
        """
        Strategy C: Generator-based discovery for minimal memory.
        
        Yields atom IDs one at a time. Peak memory: <1MB above tokenizer.
        
        Args:
            target: Stop after finding this many atoms
            mode: "space" or "did"
        
        Yields:
            Atom IDs one at a time
        """
        found = 0
        for i in range(self.vocab_size):
            if found >= target:
                return
            
            if mode == "space":
                if self._is_space_nonmerging(i):
                    yield i
                    found += 1
            elif mode == "did":
                if self._is_roundtrip_safe(i):
                    yield i
                    found += 1
    
    def _is_space_nonmerging(self, token_id: int) -> bool:
        """Check if a token is a space-prefixed non-merging atom."""
        try:
            tok_str = self.enc.decode([token_id])
        except Exception:
            return False
        
        if not tok_str.startswith(' ') or len(tok_str) < 2:
            return False
        if not tok_str.isprintable():
            return False
        
        concat = tok_str + tok_str
        try:
            ids = self.enc.encode(concat)
            return len(ids) == 2
        except Exception:
            return False
    
    def _is_roundtrip_safe(self, token_id: int) -> bool:
        """Check if a token is roundtrip-safe (DirectID compatible)."""
        try:
            decoded = self.enc.decode([token_id])
            re_encoded = self.enc.encode(decoded)
            return len(re_encoded) == 1 and re_encoded[0] == token_id
        except Exception:
            return False
    
    def benchmark_memory(self, bit_width: int = 15) -> Dict:
        """
        Benchmark memory usage of different discovery strategies.
        
        Returns comparative memory estimates.
        """
        import tracemalloc
        
        target = 2 ** bit_width
        results = {}
        
        # Strategy A: Pre-computed (if available)
        precomputed = load_precomputed(self.tokenizer_name)
        if precomputed:
            results["precomputed"] = {
                "peak_memory_bytes": sys.getsizeof(precomputed["space_nonmerging"]) * 4,
                "atoms_found": len(precomputed["space_nonmerging"]),
                "time_ms": 0,
                "note": "Loaded from disk (zero discovery cost)",
            }
        
        # Strategy B: Chunked (chunk_size=500)
        tracemalloc.start()
        t0 = time.time()
        atoms_b = self.discover(bit_width=bit_width, chunk_size=500, mode="space")
        t1 = time.time()
        peak_b = tracemalloc.get_traced_memory()[1]
        tracemalloc.stop()
        
        results["chunked_500"] = {
            "peak_memory_bytes": peak_b,
            "peak_memory_mb": round(peak_b / 1024 / 1024, 2),
            "atoms_found": len(atoms_b),
            "time_ms": round((t1 - t0) * 1000),
        }
        
        # Strategy C: Generator (collect into list)
        tracemalloc.start()
        t0 = time.time()
        atoms_c = list(self.stream_discover(target=target, mode="space"))
        t1 = time.time()
        peak_c = tracemalloc.get_traced_memory()[1]
        tracemalloc.stop()
        
        results["generator"] = {
            "peak_memory_bytes": peak_c,
            "peak_memory_mb": round(peak_c / 1024 / 1024, 2),
            "atoms_found": len(atoms_c),
            "time_ms": round((t1 - t0) * 1000),
        }
        
        return results


# ── CLI ────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="ByteToken Lazy Atom Discovery")
    parser.add_argument("--tokenizer", default="o200k_base")
    parser.add_argument("--scan", action="store_true",
                        help="Scan and save pre-computed atom tables")
    parser.add_argument("--benchmark", action="store_true",
                        help="Run memory benchmark")
    parser.add_argument("--bit-width", type=int, default=15)
    args = parser.parse_args()

    print("=" * 65)
    print("  ByteToken Lazy Atom Discovery")
    print("=" * 65)

    if args.scan:
        print(f"\n  Scanning {args.tokenizer}...")
        scan_and_save(args.tokenizer)
        print("  Done!")
    
    elif args.benchmark:
        print(f"\n  Benchmarking {args.tokenizer} (bit_width={args.bit_width})...")
        lazy = LazyAtomDiscovery(args.tokenizer)
        results = lazy.benchmark_memory(bit_width=args.bit_width)
        
        print(f"\n  {'Strategy':<20} {'Memory':>12} {'Atoms':>8} {'Time':>10}")
        print(f"  {'─' * 52}")
        for name, stats in results.items():
            mem = stats.get("peak_memory_mb", stats.get("peak_memory_bytes", 0) / 1024 / 1024)
            print(f"  {name:<20} {mem:>10.2f}MB {stats['atoms_found']:>8} "
                  f"{stats['time_ms']:>8}ms")
    
    else:
        # Default: discover and display
        print(f"\n  Discovering atoms for {args.tokenizer} (bw={args.bit_width})...")
        
        # Try precomputed first
        precomputed = load_precomputed(args.tokenizer)
        if precomputed:
            target = 2 ** args.bit_width
            atoms = precomputed["space_nonmerging"][:target]
            print(f"  Loaded from pre-computed table: {len(atoms)} atoms")
        else:
            print(f"  No pre-computed table found. Running lazy discovery...")
            lazy = LazyAtomDiscovery(args.tokenizer)
            atoms = lazy.discover(bit_width=args.bit_width, chunk_size=500)
            print(f"  Discovered: {len(atoms)} atoms")
        
        print(f"  Target: {2 ** args.bit_width} atoms for {args.bit_width}-bit encoding")
        print(f"  Status: {'SUFFICIENT' if len(atoms) >= 2 ** args.bit_width else 'INSUFFICIENT'}")

    print(f"\n{'=' * 65}")
